sha1sum

diff --git a/.github/workflows/deployartifact.yml b/.github/workflows/deployartifact.yml
--- a/.github/workflows/deployartifact.yml
+++ b/.github/workflows/deployartifact.yml
@@ -34,20 +34,21 @@ jobs:
       - name: checksum of download artifact  
         if: success()
         id: hash
-        run: 
-             echo ${{ github.event.client_payload.artifact_name }}
-             echo "HASH=$(sha1sum /tmp/artifactjar/${{ github.event.client_payload.artifact_name }} | awk '{ print $1 }')" >> $GITHUB_ENV
-             echo env.HASH
-             echo $GITHUB_ENV
+        run:  echo "HASH=$(sha1sum /tmp/artifactjar/${{ github.event.client_payload.artifact_name }} | awk '{ print $1 }')" >> $GITHUB_ENV
 
-      - name: compare checksum
-        run: |
-          if [ "${{ env.HASH }}" == "${{ github.event.client_payload.checksum }}" ]; then 
-              echo "The checksum are equals! successfully operations"
-          else
-              echo "The cheksum are NOT equals! failure operation."
-              exit 1;
-          fi
+             #echo ${{ github.event.client_payload.artifact_name }}
+             #echo "HASH=$(sha1sum /tmp/artifactjar/${{ github.event.client_payload.artifact_name }} | awk '{ print $1 }')" >> $GITHUB_ENV
+             #echo $HASH
+             #echo $GITHUB_ENV
+
+      #- name: compare checksum
+      #  run: |
+      #    if [ "${{ env.HASH }}" == "${{ github.event.client_payload.checksum }}" ]; then 
+      #        echo "The checksum are equals! successfully operations"
+      #    else
+      #        echo "The cheksum are NOT equals! failure operation."
+      #        exit 1;
+      #    fi
 
 # Descarga source code de la rama default para poder devolver Dockerfile y cargar la imagen ak cibtexti 
 
