quita comparativa

diff --git a/.github/workflows/deployartifact.yml b/.github/workflows/deployartifact.yml
--- a/.github/workflows/deployartifact.yml
+++ b/.github/workflows/deployartifact.yml
@@ -36,14 +36,14 @@ jobs:
         id: hash
         run: echo "HASH=$(sha1sum /tmp/artifactjar/${{ github.event.client_payload.artefact_name }} | awk '{ print $1 }')" >> $GITHUB_ENV
 
-      - name: compare checksum
-        run: |
-          if [ "${{ env.HASH }}" == "${{ github.event.client_payload.checksum }}" ]; then 
-              echo "The checksum are equals! successfully operations"
-          else
-              echo "The cheksum are NOT equals! failure operation."
-              exit 1;
-          fi
+     # - name: compare checksum
+     #   run: |
+     #     if [ "${{ env.HASH }}" == "${{ github.event.client_payload.checksum }}" ]; then 
+     #         echo "The checksum are equals! successfully operations"
+     #     else
+     #         echo "The cheksum are NOT equals! failure operation."
+     #         exit 1;
+     #     fi
 
 # Descarga source code de la rama default para poder devolver Dockerfile y cargar la imagen ak cibtexti 
 
